# (PART) Versionskontrolle und R Markdown  {-} 

```{r include = FALSE}
source("common.R")
```


# Git, GitHub, and RStudio {#version-control}

<!--Original content: https://stat545.com/git08_claim-stat545-repo.html-->

Wir wissen nicht ob Versionskontrolle bereits ein Thema war mit dem du dich beschäftigt hast. Wenn nicht, solltest du mit ein [paar Worten zu Git und GitHub](https://happygitwithr.com/big-picture.html) von *Jenny Byran* (Autorin von STAT 545) starten.

Ziel dieses Abschnitts wird es sein, dass du

1. einen [GitHub Account](https://happygitwithr.com/github-acct.html) anlegst (falls nicht schon vorhanden)

2. [Git auf deinem Computer installierst](https://happygitwithr.com/install-git.html)

3. dich bei [Git vorstellst](https://happygitwithr.com/hello-git.html)

4. alles zusammenfügst und deine [Verbindung zu GitHub testest](https://happygitwithr.com/push-pull-github.html)

5. abschließend noch RStudio ins Spiel bringst und [RStudio mit Git und GitHub verbindest](https://happygitwithr.com/rstudio-git-github.html)


**Bemerkung:** Unter 5. wirst du ermutigt deine GitHub Zugangsdaten auf deinem Computer zu speichern. Wir können diesen Schritt nur empfehlen.

Das Buch [*Happy Git and GitHub for the useR*](https://happygitwithr.com/) enthält noch viele weitere hilfreiche Git/GitHub Informationen. Auf manche kommen wir vielleicht im Laufe des Kurses noch zu sprechen. Andere sind vielleicht zu einem späteren Zeitpunkt interessant, wenn du an anspruchsvolleren Git Projekten arbeitest.



# R Markdown {#r-markdown}

<!--Original content: https://stat545.com/block007_first-use-rmarkdown.html-->

Ausgewählte Hausaufgaben wirst du als R Markdown Dokument abgeben. R Markdown ist eine sehr zugängliche Methode zur Erstellung von Dokumenten, die Prosa Text mit durch R-Code erzeugten Tabellen und Abbildungen kombinieren.

Ein möglicher R Markdown Workflow, der eine Interaktion mit Git, GitHub, und RStudio beinhaltet, wird vorgestellt auf der Seite:

[Test drive R Markdown](https://happygitwithr.com/rmd-test-drive.html)
